# 全局安全配置（不包含具体提示词）
global_vars:
  max_output_tokens: 512
  max_response_length: 2048

safety:
  forbidden_patterns:
    - "ignore previous instructions"
    - "disregard above"
    - "forget everything"
    - "new system prompt"
    - "override rules"
  input_filters:
    - pattern: "ignore.*previous"
      action: "reject"
    - pattern: "system.*prompt"
      action: "sanitize"
    - pattern: "prompt.*injection"
      action: "reject"
  
  # 输出限制
  max_response_length: 2048
  max_array_items: 20